### ISSUE TITLE
EA/gt6 crafting substitution problems

### ISSUE THREAD

**Issue by davethwave** [Haggle1996/Revolution4#2]
Currently you can replace certain things like using EA cheap chips and the more expensive ones which allow you to bypass a lot of stuff you normally would need to do in GT6 to be able to craft. You can also use EA rubber to make gt6 rubber things it looks like which is a mid tier material I believe in GT6.

**Comment by Haggle1996** [comment]
EA chips now require a T1 or T3 GT6 circuit to craft. Most of the base items in EA now require GT6 tools to craft and later items require more complex GT6 items, such as motors. I'll continue this pattern for mid- and late-game EA.
